### ISSUE TITLE
multi-GPU distributed learning test abbout table2text 

### ISSUE THREAD

**Issue by dong-ai-7** [awslabs/fast-differential-privacy#31]
Hi, all! Thanks for providing such great tool !
After running the command：
`bash table2text/run_ZERO1.sh table2text/prefix-tuning table2text/output "e2e" "gpt2"`
The contents of the output file (table2text/output/generations_model/eval/global_step_00000410.txt ) are just periods and empty lines. 
Is this an expected result? How to fix it?

**Comment by dong-ai-7** [comment]
OK, thanks! I will do that!

**Comment by dong-ai-7** [comment]
I noticed that the implementation of DP-Zero in the test cases (including image classification and table-to-text) defaults to using the book-keeping (BK) algorithm for DP full fine-tuning, as described in arXiv:2210.00038. 
For PEFT, the BiTFiT examples for CIFAR10 in this repository use DP-BiTFiT as described in arXiv:2210.00036. Perhaps it could be called BK-BiTFiT? 
As you mentioned, your design can be adapted to any type of PEFT and optimizer. Moreover, the appendix of the BK paper（arXiv:2210.00038） also describes the algorithms for BK-LoRA and BK-Adapter. Are there any plans to integrate these algorithms with ZeRO to enrich the current open-source library in the future?

**Comment by woodyx218** [comment]
I think DP-BiTFiT is the proper name because BK is just an implementation of DP-BiTFiT. Just like Opacus and TF-privacy both implement DP-SGD but we don't call it Opacus-SGD. As for PEFT, they are already supported by DP-ZeRO.
