### ISSUE TITLE
nn.Embedding gradients shape mismatch at backprop

### ISSUE THREAD

**Issue by mshubhankar** [awslabs/fast-differential-privacy#39]
Hi there!

I am trying to train a DP diffusion model with an embedding layer defined as `nn.Embedding(10, 256) ' using the default MixOpt mode. However, the backward pass fails when the activation shape and backdrops do not match the assumed 3D shape implementation. In my case, I have only 1-dim for A and 2-dim for B. 

`_compute_embedding_grad_sample()` function assumes arguments A and B have 3 dimensions and throws the error
> not_AAt: torch.Tensor = ~A[:, :, None].eq(A[:, None, :])
> IndexError: too many indices for tensor of dimension 1

The embedding layer definition in my model seems to be in line with the table2text implementation in [example](https://github.com/awslabs/fast-differential-privacy/blob/854805a3211ff01d0fdc98a26df386dbab95e326/examples/table2text/models.py#L32).

**Comment by woodyx218** [comment]
Do you have trouble launching the example? A and B must match in shape. One potential walkaround is to unsqueeze A.

**Comment by mshubhankar** [comment]
I tried launching the example and found out that the training model is not the exact model defined in [example](https://github.com/awslabs/fast-differential-privacy/blob/854805a3211ff01d0fdc98a26df386dbab95e326/examples/table2text/models.py#L32). The example otherwise runs fine with a minor fix I had to on [L178](https://github.dev/awslabs/fast-differential-privacy/blob/854805a3211ff01d0fdc98a26df386dbab95e326/examples/table2text/run_language_modeling.py#L178) by changing `input_embeddings_after[:-1]` to `input_embeddings_after`.

Furthermore, my A and B are not of the same shape. A is of shape [128], and B is [128,256]. I don't know what the error is here. However, I got around the issue by substituting the` nn.Embedding` module with a `nn.Linear` module without bias.

**Comment by woodyx218** [comment]
Can you provide your script if you cannot launch the table2text example? I don't understand what's "training model" and "exact model". A and B should have same dimension which is 2-dimension in your case.

**Comment by mshubhankar** [comment]
I'm sorry about the ambiguity in my last comment. It was indeed confusing. 

I was successful in running the table2text example. However, I found that the model being trained in that example is a pre-trained transformer model **without** an embedding layer.  
The PrefixTuner model, which contains the embedding layer as defined in [models.py](https://github.dev/awslabs/fast-differential-privacy/blob/854805a3211ff01d0fdc98a26df386dbab95e326/examples/table2text/models.py#L15), is not being trained in that example. 
In other words, the table2text example is **not** a good example for testing the embedding layer. Please do correct me if I am wrong. 

About my implementation. Here is the exact embedding layer definition:
`self.label_emb = nn.Embedding(num_classes, time_embed_dim)`

This is being used in the forward function as follows:
```
def forward(self, x, timesteps, y=None):
        """
        Apply the model to an input batch.
        :param x: an [N x C x ...] Tensor of inputs.
        :param timesteps: a 1-D batch of timesteps.
        :param y: an [N] Tensor of labels, if class-conditional.
        :return: an [N x C x ...] Tensor of outputs.
        """

        assert (y is not None) == (
            self.num_classes is not None
        ), "must specify y if and only if the model is class-conditional"

        hs = []
        emb = self.time_embed(timestep_embedding(timesteps, self.model_channels))
        if self.num_classes is not None:
            assert y.shape == (x.shape[0],)
            emb = emb + self.label_emb(y)
        h = x.type(self.dtype)
        for module in self.input_blocks:
            h = module(h, emb)
            hs.append(h)
        h = self.middle_block(h, emb)
        for module in self.output_blocks:
            h = th.cat([h, hs.pop()], dim=1)
            h = module(h, emb)
        h = h.type(x.dtype)
        return self.out(h)
```

**Comment by woodyx218** [comment]
The model trained in example should contain embedding layers in wte and wpe modules, because the model is instantiated from `transformers.models.gpt2.GPT2LMHeadModel`, not from models.py. Therefore, the PrefixTuner model is indeed not being trained in that example. We may remove it in the next version.
