### ISSUE TITLE
Understanding stages of deepspeed zero integration

### ISSUE THREAD

**Issue by mshubhankar** [awslabs/fast-differential-privacy#43]
I am using distributed training with FastDP and have questions about its integration with Deepspeed. This is my first time using Deepspeed, and I apologize if some of these questions are trivial:

1. Are all the three stages of Deepspeed zero necessary for distributed DPSGD training?
2. The image classification examples have two python files for stage 1 and stage 2and3. Are both of them private?
3. For stage 1, privacyengine.attach() is not recommended. Then, how is the dp_step() called?
4. The requirements file mentions older versions of torch and deepspeed. Have you tested them on any newer versions? 

Thank you!

**Comment by woodyx218** [comment]
Thank you for using FastDP! To answer you questions:

1. You only need 1 of three stages for distributed DPSGD. As you move up the stage, you trade off the communication time for memory efficiency (i.e. slower but can train larger models).
2. Yes they are all private and should give you similar results.
3. For all stages, we don't need .attach() or dp_step. The modification is on the grad, not on the optimizer, so that regular step() would work directly.
4. I haven't tested on newer versions.

**Comment by SMohapatra-sony** [comment]
Thanks for your reply. I also read about it later in your [paper](https://arxiv.org/abs/2311.11822). 
FastDP generally has been great in my experience.
I might have a partial answer to 4 now. Yes, torch>=2.2.0 works with some extra warnings but is generally fine. 
However, I think the deepspeed integration fails with later versions >=0.8.3. Also, I haven't tested it completely but with my current setup (torch==2.1.0, deepspeed==0.8.3 and transformers==4.30.0), mixed precision using fp16 mode isn't working as expected. The bf16 is good.

**Comment by mshubhankar** [comment]
Thanks for your reply. I also read about it later in your [paper](https://arxiv.org/abs/2311.11822). 
FastDP generally has been great in my experience.
I might have a partial answer to 4 now. Yes, torch>=2.2.0 works with some extra warnings but is generally fine. 
However, I think the deepspeed integration fails with later versions >=0.8.3. Also, I haven't tested it completely but with my current setup (torch==2.1.0, deepspeed==0.8.3 and transformers==4.30.0), mixed precision using fp16 mode isn't working as expected. The bf16 is good.

**Comment by woodyx218** [comment]
Good to know and thank you for your liking! Indeed, FP16 needs to turn off loss scaling (unlike nonDP training) and I do recommend bf16 as default.
